#!/usr/bin/env bash

OUTPUT1="eDP1"
OUTPUT2="DP2-1"
OUTPUT3="DP1-2"

if [ "$1" = "dual4k" ]; then
    xrandr --output VIRTUAL1 --off \
        --output eDP1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
        --output DP1-2 --mode 3840x2160 --pos 1920x0 --rotate normal \
        --output DP1 --off \
        --output HDMI2 --off \
        --output HDMI1 --off \
        --output DP1-3 --off \
        --output DP1-1 --off \
        --output DP2 --off
fi

if [ "$1" = "laptop" ]; then
    xrandr --output VIRTUAL1 --off \
        --output $OUTPUT1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP1 --off \
        --output HDMI2 --off \
        --output HDMI1 --off \
        --output DP1-3 --off \
        --output DP1-2 --off \
        --output DP1-1 --off \
        --output DP2 --off
fi

if [ "$1" = "2" ]; then
        xrandr --output VIRTUAL1 --off \
        --output $OUTPUT1 --off \
        --output DP1 --off \
        --output HDMI2 --off \
        --output DP2-2 --off \
        --output DP2-3 --off \
        --output HDMI1 --off \
        --output DP1-3 --off \
        --output $OUTPUT2 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
        --output $OUTPUT3 --mode 3840x2160 --pos 1920x0 --rotate normal \
        --output DP-1-1 --off \
        --output DP2 --off
fi

if [ "$1" = "3" ]; then
    xrandr --output VIRTUAL1 --off \
        --output $OUTPUT1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
        --output $OUTPUT3 --mode 3840x2160 --pos 1920x0 --rotate normal \
        --output $OUTPUT2 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP1 --off \
        --output HDMI2 --off \
        --output DP2-2 --off \
        --output DP2-3 --off \
        --output HDMI1 --off \
        --output DP1-3 --off \
        --output DP1-1 --off \
        --output DP2 --off
fi
#xrandr --output $LAPTOP --auto --right-of $MONITOR --output $MONITOR --mode 3840x2160
